(function(k,m,h,g,l){k[m]=k[m]||{};for(k[m].q=k[m].q||[];l<g.length;)h(g[l++],k[m])})(window,"extole",function(k,m){m[k]=m[k]||function(){m.q.push([k,arguments])}},["log"],0);
extole.define||function(){function k(){}function m(){var a="undefined"!==typeof opera&&"[object Opera]"===opera.toString(),b=document.createElement("script");this.useInteractive=b.attachEvent&&!(b.attachEvent.toString&&0>b.attachEvent.toString().indexOf("[native code"))&&!a}var h=[],g=function(a){var b;f(h,function(c){if(d(c.url)==d(a))return b=c,!1});return b},l=function(a){extole.log("debug","[REQUIRE] "+a)},n=function(a){extole.log("error","[REQUIRE] "+a)},f=function(a,b){if(a.length)for(var c=
0;c<a.length;c++)b(a[c],c);else for(c in a)a.hasOwnProperty(c)&&b(a[c],c)},e=function(a,b){var c=[];f(a,function(a,d){c[d]=b(a,d)});return c},d=function(a){return"string"!==typeof a?a:a.match(/origin-\d/)?a.substring(a.indexOf("type=")).replace(/version=\d+:/,""):a},c=function(a){var b=a.split("/").slice(-1)[0],c=b.length;f(b.toLowerCase(),function(a){c+=" abcdefghijklmnopqrstuvwxyz1234567890-_.".indexOf(a)});return a.replace("origin","origin-"+c%8)},b=function(a){var d=!!a.match(/^extole-creatives:/),
p=!!a.match(/^extole-media:/),e=!!a.match(/^core-root:\/\//),q=!!a.match(/^extole-assets:/),f=!!a.match(/origin\./),l=!!a.match(/^http:/),g=!!a.match(/^https:/);return d?(a=a.slice(17),b("extole-assets:/core-modules/"+a)):q?(a=a.slice(14),a="extole-media:/assets/"+a,b(a)):p?(a=a.slice(13),a=extole.CORE_ROOT+a,b(a)):e?(a=a.slice(12),a=extole.CORE_ROOT+a,b(a)):f?(a=c(a),a+="?site="+window.location.hostname,b(a)):l?(a=a.slice(5),b(a)):g?(a=a.slice(6),b(a)):a};k.prototype={getUnresolvedDependencies:function(){var a=
[];f(this.dependencies,function(b){"$config"!=b&&(b=g(b),(!b||b&&!b._defined)&&a.push(b))});return a},getDependencies:function(){var a=this,b=[];f(a.dependencies,function(c){c="$config"==c?a.config||null:g(c).definition||null;b.push(c)});return b},define:function(){var b=this;b.defineStartTime=b.defineStartTime||(new Date).getTime();if(!b._defining&&!b._defined&&b.dependencies)if(b._defining=!0,0<b.getUnresolvedDependencies().length)b._defining=!1;else{var c=function(c){b.definedCallback=void 0;b.definition=
c;b.end=(new Date).getTime();b.timeToDefine=b.end-b.start;b.timeToFetch&&l("Fetched "+b.url+" in "+b.timeToFetch+"ms");b.isAsync&&l("Defined async "+b.url+" in "+b.timeToDefine+"ms");b._defining=!1;b._defined=!0;setTimeout(a,1)},d=b.getDependencies(),p={isAsync:!1,async:function(){p.isAsync=b.isAsync=!0;return function(a){c(a)}}};(function(){if(b.definedCallback){var a=b.definedCallback,a=a&&a.apply(p,d);p.isAsync||c(a)}else c(!0)})()}},fetch:function(){var a=this;a._fetching||a._fetched||(a.url?
(a._fetching=!0,a.startFetchTime=(new Date).getTime(),p.loadModule(a.url,function(){a._fetching=!1;a.endFetchTime=(new Date).getTime();a.timeToFetch=a.endFetchTime-a.startFetchTime;a._fetched=!0;a.define()})):n("Tried to fetch a module without a url - dependencies: "+a.dependencies+" definedCallback: "+(a.definedCallback?"exists":"null")+" config: "+a.config))}};m.prototype={defineQueue:[],interactiveScript:null,currentlyAddingScript:null,getInteractiveScript:function(){if(p.interactiveScript&&"interactive"==
p.interactiveScript.readyState)return p.interactiveScript;for(var a=document.getElementsByTagName("head")[0].getElementsByTagName("script"),b,c=a.length-1;0<=c;c--){var d=this.getScriptDataUrl(a[c]);a[c]&&"interactive"==a[c].readyState&&d&&(b=a[c],l("...interactive script "+b.src))}return b},scriptUrlAttributeName:"data-extole-require-url",getScriptDataUrl:function(a){return a.getAttribute(this.scriptUrlAttributeName)},setScriptDataUrl:function(a,b){a.setAttribute(this.scriptUrlAttributeName,b)},
attachOnLoad:function(a,b){b=b||function(){};var c=this.useInteractive,d="PLAYSTATION 3"===navigator.platform?/^complete$/:/^(complete|loaded)$/,p=function(e){var q=a.readyState;if(c&&"interactive"==q)interactiveScript=a;else if("load"===e.type||q.match(d))c?a.detachEvent("onreadystatechange",p):a.removeEventListener("load",p,!1),l(a.src+" finished loading"),b(e)};c?a.attachEvent("onreadystatechange",p):a.addEventListener("load",p,!1)},defineTimeout:null,addDefine:function(a){if(a.url)a.url=b(a.url);
else{l("defining anonymous module...");var c=this.currentlyAddingScript||this.getInteractiveScript();this.useInteractive&&c?(c=this.getScriptDataUrl(c),l("..scriptToCompare has data url "+c),a.url=c,this.interactiveScript=null):this.useInteractive&&l("..found no scriptToCompare")}a.dependencies=e(a.dependencies,b);this.useInteractive&&!a.url&&n("defines should not be missing a url in ie.");this.defineQueue.push(a);this.defineTimeout&&clearTimeout(this.defineTimeout);var d=this;this.defineTimeout=
setTimeout(function(){l("intakeDefines from addDefine timeout");d.intakeDefines()},1)},intakeTimeout:null,intakeDefines:function(){for(var b={},c=function(a,c){b[a]=b[a]?b[a]+","+c:c},d=[],p;p=this.defineQueue.shift();){var e=[];f(p.dependencies,function(a){a&&e.push(a)});var h=p.url&&g(p.url);p.url?h?c(p.url,"updated"):c(p.url,"created"):d.push("deps "+p.dependencies);f(e,function(a){c(a,"dependency");q(a)});q(p.url,e,p.definedCallback,p.config,p.isRequire)}var w="intakeDefines -- ";f(b,function(a,
b){w+="\n - "+b+" "+a});w+="\n -- "+d.length+" anonymous modules created";f(d,function(a){w+="\n - "+a});l(w);this.intakeTimeout&&clearTimeout(this.intakeTimeout);this.intakeTimeout=setTimeout(a,1)},loadModule:function(a,b){var c=document.createElement("script");c.async=!0;c.crossOrigin="anonymous";this.setScriptDataUrl(c,a);var p=this;l("loading module "+a);this.attachOnLoad(c,function(){if(!p.useInteractive){for(var c,d=p.defineQueue.length-1;0<=d;d--)p.defineQueue[d].url||(c&&n("Multiple anonymous modules loaded in one script - "+
a),c=p.defineQueue[d]);c?(l("assigned "+a+" to anonymous module"),c.url=a):l("module url didn't define a module - "+a)}l("intake defines from loadModule");p.intakeDefines();b&&b(null)});c.src=a;this.currentlyAddingScript=c;var d=document.getElementsByTagName("head")[0]||document.head;d?d.appendChild(c):extole.log("warn","[REQUIRE] <head> element not found on trying to load "+a);this.currentlyAddingScript=void 0}};var p=new m,a=function(){f(h,function(a){a._fetched?a._defined||a.define():a.fetch()})},
q=function(a,b,c,p,d){if("$config"!=a){var e=g(a),q=e||new k;e||h.push(q);a&&b&&(q._fetched=!0);q.start=q.start||(new Date).getTime();q.url=q.url||a;q.dependencies=q.dependencies||b;q.config=q.config||p;q.definedCallback=q.definedCallback||c;q.isRequire=q.isRequire||d}},w=function(a,b,c,d){a instanceof Array&&(d=c,c=b,b=a,a=void 0);p.addDefine({url:a,dependencies:b,definedCallback:c,config:d})};w.getModule=function(a){return g(a)};var y=0,x=function(){y++;return"anonymous_"+y};extole.define=w;extole.require=
function(a,b){p.addDefine({url:x(),dependencies:a,definedCallback:b,isRequire:!0})};extole.define("extole-require",[],function(){return{resolveUrl:b}});setTimeout(function(){var a=!1,b=[];f(h,function(c){c._defined||(a=!0);b.push({defineStartTime:c.defineStartTime,dependencies:c.dependencies,end:c.end,start:c.start,isRequire:c.isRequire,timeToDefine:c.timeToDefine,url:c.url,_defined:c._defined,_defining:c._defining,_fetched:c._fetched})});a&&extole.DUMP_REQUIRE_MODULES_ON_ERROR&&extole.log("error",
"After 7000ms there are unresolved extole-require modules.  ###"+JSON.stringify(b)+"###")},7E3)}();(function(){})();(function(k,m,h,g,l){k[m]=k[m]||{};for(k[m].q=k[m].q||[];l<g.length;)h(g[l++],k[m])})(window,"extole",function(k,m){m[k]=m[k]||function(){m.q.push([k,arguments])}},["createZone","log"],0);
(function(){var k=[{name:"Rebecca Minkoff Referral Program",programDomain:"referafriend.rebeccaminkoff.com",sitePatterns:"rm.qa-1.blueacorn.net *.uriminkoff.com staging-rebecca-minkoff.myshopify.com *.rebeccaminkoff.com api.extole.com rebecca-minkoff.myshopify.com uriminkoff.com *.rebeccaminkoff.com\\.?$ *.rm.qa-1.blueacorn.net\\.?$ *.rebecca-minkoff.myshopify.com\\.?$ *.uriminkoff.com\\.?$ *.extole.com *.rmstaging.rebeccaminkoff.com\\.?$ referafriend.rebeccaminkoff.com *.referafriend.rebeccaminkoff.com\\.?$ *.extole.io *.staging-rebecca-minkoff.myshopify.com\\.?$ rmstaging.rebeccaminkoff.com".split(" "),isSecure:!1}];
extole.CORE_ROOT="https://origin.extole.io/type=core:clientId=1241766588:coreAssetsVersion=1544591110231";extole.CORE_CONFIG={backendTargetingEnabled:!0,cookieConsentEnabled:!1};extole.CLIENT_ID="1241766588";extole.BUILD_DATE="1559074590202";extole.VERSION="6.0";extole.PROGRAM=function(){var m=function(e,d){var c=Error.call(this,e);this.name="ExtoleError";this.message=c.message;this.stack=c.stack;this.code=d};m.prototype=Error();m.prototype.constructor=m;var h=function(e,d){if(e.length)for(var c=
0;c<e.length;c++)d(e[c],c);else for(c in e)e.hasOwnProperty(c)&&d(e[c],c)},g=function(e,d){var c=[];h(e,function(b){(b=d(b))&&(c[c.length]=b)});return c},l=function(e,d){d=d||[];var c=!1;h(d,function(b){(new RegExp(b.replace(/\./g,"\\.").replace(/\*/g,".*"))).test(e)&&(c=!0)});return c},n=function(e){var d=window.location.hostname;return g(e,function(c){if(l(d,c.sitePatterns))return c})}(k),f=n[0];if(!f)throw new m("No program domain is configured for hostname: "+window.location.hostname+" unable to use Extole API",
"site_configuration_error");1<n.length&&extole.log("warn","Multiple programs matched hostname: "+window.location.hostname+" programs: "+JSON.stringify(n));return f}();extole.require(["https://origin.extole.io/type=core:clientId=1241766588:coreAssetsVersion=1544591110231/common/collection.js","https://origin.extole.io/type=core:clientId=1241766588:coreAssetsVersion=1544591110231/common/uri.js","https://origin.extole.io/type=core:clientId=1241766588:coreAssetsVersion=1544591110231/common/logger.js",
"create-zone-executor"],function(k,h,g,l){var n=function(){function c(c){var a=c[0];"function"===typeof b[a]?b[a].apply(null,c[1]):g.warn("Unable to execute method: "+a+", it is not implemented.")}for(var b={log:function(){var b=Array.prototype.slice.call(arguments),a=b[0];"function"===typeof g[a]&&g[a].apply(null,b.slice(1))},createZone:l.execute};extole.q.length;)c(extole.q.shift());extole.q.push=c},f=function(){var c=function(a){var b={},c=/^extole_/,d=/^extole_zone_/;k.each(a,function(a,p){p.match(d)?
b[p.replace(d,"")]=a:p.match(c)&&(b[p.replace(c,"")]=a)});return b}(h.deserialize(window.location.search));if(c.name){var b=c.name,d=c.element_id;delete c.name;delete c.element_id;extole.createZone({name:b,element_id:d,data:c})}},e=function(){var c;"function"===typeof window.onerror&&(c=window.onerror);window.onerror=function(b,d,a,e,f){if(c)try{c(b,d,a,e,f)}catch(l){}d=d||window.location.href||"no_source_or_location.href";f=f&&f.stack?f.stack:"no_error.stack";var g=[],h=JSON.stringify({MESSAGE:b,
SOURCE:d,LINE_NUMBER:a,COLUMN_NUMBER:e,STACK_TRACE:f},function(a,b){if(null!==b&&"object"==typeof b){if(0<=g.indexOf(b))return;g.push(b)}return b});((f+b).match(/extole/i)||d.match(extole.PROGRAM.programDomain))&&extole.require(["https://origin.extole.io/type=core:clientId=1241766588:coreAssetsVersion=1544591110231/common/logger.js"],function(a){a.error("Unhandled exception",JSON.parse(h))})}},d=function(){extole._bootstrapped=!0;e();n();f()};extole.bootstrap=d;extole._bootstrapped||d();if("undefined"!==
typeof window.extoleAsyncInit)try{extoleAsyncInit()}catch(c){extole.require(["https://origin.extole.io/type=core:clientId=1241766588:coreAssetsVersion=1544591110231/common/logger.js"],function(b){b.error("Error executing extended core javascript. Message : "+c.message+" Stack: "+c.stack)})}})})();
extole.define("https://origin.extole.io/type=core:clientId=1241766588:coreAssetsVersion=1544591110231/common/JSON.js",[],function(){var k;"object"!==typeof k&&(k={});(function(){function m(b){return 10>b?"0"+b:b}function h(b){n.lastIndex=0;return n.test(b)?'"'+b.replace(n,function(b){var a=d[b];return"string"===typeof a?a:"\\u"+("0000"+b.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+b+'"'}function g(b,d){var a,q,l,k,n=f,t,r=d[b];r&&r instanceof Date&&(a=r,r=isFinite(a.valueOf())?a.getUTCFullYear()+
"-"+m(a.getUTCMonth()+1)+"-"+m(a.getUTCDate())+"T"+m(a.getUTCHours())+":"+m(a.getUTCMinutes())+":"+m(a.getUTCSeconds())+"Z":null);"function"===typeof c&&(r=c.call(d,b,r));switch(typeof r){case "string":return h(r);case "number":return isFinite(r)?String(r):"null";case "boolean":case "null":return String(r);case "object":if(!r)return"null";f+=e;t=[];if("[object Array]"===Object.prototype.toString.apply(r)){k=r.length;for(a=0;a<k;a+=1)t[a]=g(a,r)||"null";l=0===t.length?"[]":f?"[\n"+f+t.join(",\n"+f)+
"\n"+n+"]":"["+t.join(",")+"]";f=n;return l}if(c&&"object"===typeof c)for(k=c.length,a=0;a<k;a+=1)"string"===typeof c[a]&&(q=c[a],(l=g(q,r))&&t.push(h(q)+(f?": ":":")+l));else for(q in r)Object.prototype.hasOwnProperty.call(r,q)&&(l=g(q,r))&&t.push(h(q)+(f?": ":":")+l);l=0===t.length?"{}":f?"{\n"+f+t.join(",\n"+f)+"\n"+n+"}":"{"+t.join(",")+"}";f=n;return l}}var l,n,f,e,d,c;"function"!==typeof k.stringify&&(n=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
d={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},k.stringify=function(b,d,a){var q;e=f="";if("number"===typeof a)for(q=0;q<a;q+=1)e+=" ";else"string"===typeof a&&(e=a);if((c=d)&&"function"!==typeof d&&("object"!==typeof d||"number"!==typeof d.length))throw Error("JSON.stringify");return g("",{"":b})});"function"!==typeof k.parse&&(l=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,k.parse=function(b,c){function a(b,
d){var e,q,f=b[d];if(f&&"object"===typeof f)for(e in f)Object.prototype.hasOwnProperty.call(f,e)&&(q=a(f,e),void 0!==q?f[e]=q:delete f[e]);return c.call(b,d,f)}var d;b=String(b);l.lastIndex=0;l.test(b)&&(b=b.replace(l,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(b.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return d=eval("("+
b+")"),"function"===typeof c?a({"":d},""):d;throw new SyntaxError("JSON.parse");})})();return k});
extole.define("https://origin.extole.io/type=core:clientId=1241766588:coreAssetsVersion=1544591110231/common/collection.js",["https://origin.extole.io/type=core:clientId=1241766588:coreAssetsVersion=1544591110231/common/type.js"],function(k){var m=function(l,g){var f=Error.call(this,l);this.name="ExtoleError";this.message=f.message;this.stack=f.stack;this.code=g};m.prototype=Error();m.prototype.constructor=m;var h=function(l,g){var f,e;if(l.length===+l.length)for(e=0;e<l.length;e++){if(f=g(l[e],e),
!1===f)return!1}else for(e in l)if(l.hasOwnProperty(e)&&(f=g(l[e],e),!1===f))return!1};h.BREAK=!1;var g=function(l){if(!l||"object"!==typeof l&&!k.isPlainFunction(l))l={};for(var h=1;h<arguments.length;h++)if(k.isPlainObject(arguments[h]))for(var f in arguments[h]){var e=arguments[h][f];e!==l&&void 0!==e&&(k.isPlainObject(e)&&k.isPlainObject(l[f])?e=g(l[f],e):k.isArray(e)&&k.isArray(l[f])&&l[f].concat&&(e=l[f].concat(e)),l[f]=e)}return l};return{each:h,map:function(l,g){function f(c,b){d=[];h(c,function(c,
a){d.push(b(c,a))})}function e(c,b){d={};h(c,function(c,a){d[a]=b(c,a)})}var d;if(k.isArray(l))f(l,g);else if(k.isPlainObject(l))e(l,g);else throw new m(l+" argument must be type object or array","INVALID_ARGUMENT_EXCEPTION");return d},filter:function(g,n){function f(c,b){d=[];h(c,function(c,a){b(c,a)&&d.push(c)})}function e(c,b){d={};h(c,function(c,a){b(c,a)&&(d[a]=c)})}var d;if(k.isArray(g))f(g,n);else if(k.isPlainObject(g))e(g,n);else throw new m(g+" argument must be type object or array","INVALID_ARGUMENT_EXCEPTION");
return d},merge:g}});
extole.define("https://origin.extole.io/type=core:clientId=1241766588:coreAssetsVersion=1544591110231/common/cookie.js",["https://origin.extole.io/type=core:clientId=1241766588:coreAssetsVersion=1544591110231/common/logger.js"],function(k){function m(e){try{return decodeURIComponent(e.replace(l," "))}catch(d){return k.info("** cookie.decode ** Cookie error for: "+e,{error:d,message:d.message,stack:d.stack,cookiePart:e}),""}}function h(e){e=m(e);return 0===e.indexOf('"')?e.slice(1,-1).replace(n,'"').replace(f,
"\\"):e}function g(e){if(!e||!e.toUTCString){var d=new Date;d.setDate(d.getDate()+("number"===typeof e?e:0));return d}return e}var l=/\+/g,n=/\\"/g,f=/\\\\/g;return function(e,d,c){if(void 0!==d)return c=c||{},document.cookie=[encodeURIComponent(e),"=",encodeURIComponent(d),c.expires?"; expires="+g(c.expires).toUTCString():"",c.path?"; path="+c.path:"",c.domain?"; domain="+c.domain:"",c.secure?"; secure":""].join("");a:{d=document.cookie?document.cookie.split("; "):[];c=e?null:{};for(var b=0,p=d.length;b<
p;b++){var a=d[b].split("="),f=m(a[0]);if(!e)c[f]=h(a[1]);else if(e===f){e=h(a[1]);break a}}e=c}return e}});
extole.define("https://origin.extole.io/type=core:clientId=1241766588:coreAssetsVersion=1544591110231/common/dom.js",[],function(){var k={each:function(c,b){var d,a;if(c.length===+c.length)for(a=0;a<c.length;a++){if(d=b(c[a],a),!1===d)return!1}else for(a in c)if(c.hasOwnProperty(a)&&(d=b(c[a],a),!1===d))return!1},extend:function(){var c,b,d,a,e,f=arguments[0]||{},g=1,h=arguments.length,l=!1,k=this.extend;"boolean"===typeof f&&(l=f,f=arguments[1]||{},g=2);for("object"===typeof f||this.isFunction(f)||
(f={});g<h;g++)if(c=arguments[g],null!==c)for(b in c)d=f[b],a=c[b],f!==a&&(l&&a&&(this.isPlainObject(a)||(e=this.isArray(a)))?(e?(e=!1,d=d&&isArray(d)?d:[]):d=d&&isPlainObject(d)?d:{},f[b]=k(l,d,a)):void 0!==a&&(f[b]=a));return f},isFunction:function(c){return c&&"function"===typeof c&&c.call&&c.apply},isPlainObject:function(c){if("[object Object]"!==String(c)||c.nodeType||c.window&&c.window==c)return!1;try{if(c.constructor&&!c.constructor.prototype.hasOwnProperty("isPrototypeOf"))return!1}catch(b){return!1}return!0},
isArray:function(c){return c instanceof Array}};k.each.BREAK=!1;var m=function(){var c=[],b=function(a,b,d){for(var e=[],p=0;p<c.length;p++){var f=c[p];f.element==a&&f.eventType==b&&f.listener==d&&e.push({index:p,eventListener:f})}return e},d=function(a){this.originalEvent=a;this.type=a.type;this.keyCode=a.keyCode;this.target=a.srcElement?a.srcElement:a.target};d.prototype={preventDefault:function(){var a=this.originalEvent;a.preventDefault?a.preventDefault():a.returnValue=!1},stopPropagation:function(){var a=
this.originalEvent;a.stopPropagation&&a.stopPropagation();a.cancelBubble=!0}};return{addListener:function(a,e,f){if(0<b(a,e,f).length)console.warn("events.add - Listener already exists for event "+e+" on element "+a);else{var g=!a.addEventListener,h=function(b){g&&(b=window.event);return f.call(a,new d(b))};c.push({element:a,eventType:e,listener:f,listenerWrapper:h});a.addEventListener?a.addEventListener(e,h,!1):a.attachEvent("on"+e,h)}},triggerEvent:function(a,b,c){var d=document.createEvent("Event");
d.initEvent(b,!0,!1);k.extend(d,c);a.dispatchEvent(d)},removeListener:function(a,d,e){e=b(a,d,e);0>=e.length?console.warn("events.remove - Couldn't find exiting event listener for type \""+d+'" listener on element '+a):k.each(e,function(b){var e=b.index;b=b.eventListener;a.removeEventListener?a.removeEventListener(d,b.listenerWrapper,!1):a.detachEvent("on"+d,b.listenerWrapper);c.splice(e,1)})}}}(),h=function(){var c=function(b){b=b.className;var a={};if(!b)return a;k.each(b.split(" "),function(b){a[b]=
1});return a},b=function(b){var a="";k.each(b,function(b,c){a+=" "+c});return a.slice(1)};return{setAttribute:function(b,a,c){b.setAttribute(a,c);b[a]=c},getAttribute:function(b,a){return b.getAttribute(a)},addClass:function(d,a){var e=c(d);e[a]||(e[a]=1,d.className=b(e))},removeClass:function(d,a){var e=c(d);delete e[a];d.className=b(e)},getClassNames:function(b){return b.className.split(" ")}}}(),g=function(){var c=function(b){var a=document.createDocumentFragment(),c=document.createElement("div");
c.innerHTML=b;k.each(c.childNodes,function(b){1==b.nodeType&&a.appendChild(b)});return a},b=function(b){var a;k.each(b.childNodes,function(b){if(!a&&1==b.nodeType)return a=b,k.each.BREAK});return a};return{prepend:function(d,a){var e=b(d),f=a;"string"==typeof a&&(f=c(a));e?d.insertBefore(f,e):d.appendChild(f)},append:function(b,a){var d=a;"string"==typeof a&&(d=c(a));b.appendChild(d)}}}(),l=function(c,b){return(b||document).querySelectorAll(c)},n=function(c,b){return l(c,b)[0]},f={},e=function(c,
b){function e(){b&&(b(a),b=!1,d.removeEventListener(a,"load",e))}if(f[c]||!c)return b(f[c]),f[c]||null;var a=f[c]=document.createElement("link");d.setAttribute(a,"rel","stylesheet");d.setAttribute(a,"href",c);d.append(d.queryFirst("head"),a);d.addEventListener(a,"load",e);setTimeout(e,5E3);return a},d={addEventListener:m.addListener,removeEventListener:m.removeListener,triggerEvent:m.triggerEvent,getAttribute:h.getAttribute,setAttribute:h.setAttribute,addClass:h.addClass,removeClass:h.removeClass,
getClassNames:h.getClassNames,prepend:g.prepend,append:g.append,query:l,queryFirst:n,isVisible:function(c,b){return Boolean((n(c,b)||{}).offsetParent)},injectStylesheet:e,injectStylesheets:function(c,b){function d(c){!--a&&b&&b(f)}if(0===c.length)b();else{var a=0,f=[];k.each(c,function(b){a++;setTimeout(function(){f.push(e(b,d))},1)})}}};return d});
extole.define("https://origin.extole.io/type=core:clientId=1241766588:coreAssetsVersion=1544591110231/common/event-bus.js",[],function(){function k(){this._events={};var g=/\s+/,l=function(f,e,d,c){if(!d)return!0;if("object"===typeof d){for(var b in d)f[e].apply(f,[b,d[b]].concat(c));return!1}if(g.test(d)){d=d.split(g);b=0;for(var p=d.length;b<p;b++)f[e].apply(f,[d[b]].concat(c));return!1}return!0},k=function(f,e){var d,c=-1,b=f.length,p=e[0],a=e[1],g=e[2];switch(e.length){case 0:for(;++c<b;)(d=f[c]).callback.call(d.ctx);
break;case 1:for(;++c<b;)(d=f[c]).callback.call(d.ctx,p);break;case 2:for(;++c<b;)(d=f[c]).callback.call(d.ctx,p,a);break;case 3:for(;++c<b;)(d=f[c]).callback.call(d.ctx,p,a,g);break;default:for(;++c<b;)(d=f[c]).callback.apply(d.ctx,e)}};this.on=function(f,e,d){if(!l(this,"on",f,[e,d])||!e)return this;this._events||(this._events={});(this._events[f]||(this._events[f]=[])).push({callback:e,context:d,ctx:d||this});return this};this.off=function(f,e,d){var c,b,p,a,g,k,n,m;if(!this._events||!l(this,"off",
f,[e,d]))return this;if(!f&&!e&&!d)return this._events=void 0,this;a=f?[f]:h.keys(this._events);g=0;for(k=a.length;g<k;g++)if(f=a[g],p=this._events[f]){this._events[f]=c=[];if(e||d)for(n=0,m=p.length;n<m;n++)b=p[n],(e&&e!==b.callback&&e!==b.callback._callback||d&&d!==b.context)&&c.push(b);c.length||delete this._events[f]}return this};this.once=function(f,e,d){var c=this,b=function(){var p=m.call(arguments);e.apply(this,p);c.off(f,b,d)};this.on(f,b,d);return this};this.trigger=function(f){if(!this._events)return this;
var e=m.call(arguments,1);if(!l(this,"trigger",f,e))return this;var d=this._events[f],c=this._events.all;d&&k(d,e);c&&k(c,arguments);return this}}var m=Array.prototype.slice,h={isPlainObject:function(g){if("[object Object]"!==String(g)||g.nodeType||g.window&&g.window==g)return!1;try{if(g.constructor&&!g.constructor.prototype.hasOwnProperty("isPrototypeOf"))return!1}catch(h){return!1}return!0},keys:function(g){if(!this.isPlainObject(g))return[];var h=[],k;for(k in g)has(g,k)&&h.push(k);return h},_idCounter:0,
uniqueId:function(g){var h=++this._idCounter+"";return g?g+h:h}};return{create:function(){return new k}}});
extole.define("https://origin.extole.io/type=core:clientId=1241766588:coreAssetsVersion=1544591110231/common/logger.js",[],function(){function k(d,c,b){b=b||{};b.pageId=g;b.referer=l;var p;try{p=[c||"no message","START_JSON",JSON.stringify(b),"END_JSON"].join(" ")}catch(a){h("Failed to stringify log's json data",{exception:a});return}extole.LOG_EXCLUDE_REGEX&&p.match(extole.LOG_EXCLUDE_REGEX)||(e[p]=++e[p]||1,n[d]>=n[extole.LOG_LEVEL_CONSOLE]&&window.console&&window.console.log&&window.console.log(d+
" "+p),n[d]>=n[extole.LOG_LEVEL_REMOTE]&&(c=e[p],f[c]&&m(d,p+(1<c?" log count: "+c:""))))}function m(d,c){extole.require(["https://origin.extole.io/type=core:clientId=1241766588:coreAssetsVersion=1544591110231/common/api.js"],function(b){var e="/api/v4/debug/logs",a;a:{a=document.cookie.split(";");for(var f=0;f<a.length;f++){var g=a[f].replace(/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g,"");if(0===g.indexOf("extole_access_token=")){a=g.substring(20,g.length);break a}}a=null}a&&"null"!=a&&"undefined"!=a&&
(e+="?access_token="+a);b.post(e,{level:d,message:c})})}function h(d,c){k("ERROR",d,c)}var g=String((new Date).getTime()),l=window.location.href,n={DEBUG:0,INFO:1,WARN:2,ERROR:3,OFF:4},f={1:!0,3:!0,10:!0,30:!0,100:!0,250:!0,500:!0,1E3:!0};extole.LOG_EXCLUDE_REGEX=extole.LOG_EXCLUDE_REGEX||void 0;extole.LOG_LEVEL_CONSOLE=extole.LOG_LEVEL_CONSOLE||"OFF";extole.LOG_LEVEL_REMOTE=extole.LOG_LEVEL_REMOTE||"WARN";var e={};return{debug:function(d,c){k("DEBUG",d,c)},info:function(d,c){k("INFO",d,c)},warn:function(d,
c){k("WARN",d,c)},error:h,LOGGING_ENDPOINT:"/api/v4/debug/logs"}});extole.define("https://origin.extole.io/type=core:clientId=1241766588:coreAssetsVersion=1544591110231/common/Timer.js",[],function(){return function(){var k=this,m;this.start=function(){if(m)throw Error("Timer.start has already been called");m=new Date;return k};this.getElapsedTime=function(){if(!m)throw Error("Timer has not been started");return new Date-m}}});
extole.define("https://origin.extole.io/type=core:clientId=1241766588:coreAssetsVersion=1544591110231/common/type.js",[],function(){var k=function(h,g){return function(l){return m(h,l,g)}},m=function(h,g,l){l=l||{};h=Object.prototype.toString.call(g)==="[object "+h+"]";g=g&&l.construct?g.constructor===l.construct:!0;return(l.negate?!h:h)&&g};return{isPlainObject:k("Object",{construct:Object}),isPlainFunction:k("Function"),isArray:k("Array"),isString:k("String"),isBoolean:k("Boolean"),isUndefined:k("Undefined"),
isDefined:k("Undefined",{negate:!0}),isNull:k("Null"),test:m}});
extole.define("https://origin.extole.io/type=core:clientId=1241766588:coreAssetsVersion=1544591110231/common/uri.js",[],function(){function k(h){var g={};(function n(f,e){for(var d in f){var c=f[d],b=(e?e+".":"")+d;"[object Object]"===Object.prototype.toString.call(c)?n(c,b):g[b]=c}})(h);return g}function m(h){try{return decodeURIComponent(h)}catch(g){return h}}return{serialize:function(h){var g="",l;for(l in h)g+="&"+encodeURIComponent(l)+"="+encodeURIComponent(String(h[l]));return g.replace(/^\&/,
"?")},deserialize:function(h){var g={};if(!h)return g;h=(h.match(/^\?/)?h.slice(1):h).split("&");for(var l=0;l<h.length;l++){var k=h[l].split("=");g[m(k[0])]=m(k[1])}return g},objectToDotNotation:k,dotNotationToObject:function(h){var g={};h=k(h);for(var l in h){for(var n=g,f=l.split("."),e=f.pop();f.length;)var d=f.shift(),n=n[d]=n[d]||{};n[e]=h[l]}return g},decodeComponent:m,encodeComponent:function(h){return encodeURIComponent(h)}}});
extole.define("https://origin.extole.io/type=core:clientId=1241766588:coreAssetsVersion=1544591110231/common/ajax.js",["https://origin.extole.io/type=core:clientId=1241766588:coreAssetsVersion=1544591110231/common/collection.js","https://origin.extole.io/type=core:clientId=1241766588:coreAssetsVersion=1544591110231/common/uri.js","https://origin.extole.io/type=core:clientId=1241766588:coreAssetsVersion=1544591110231/common/type.js","https://origin.extole.io/type=core:clientId=1241766588:coreAssetsVersion=1544591110231/common/logger.js"],
function(k,m,h,g){var l=[function(){return new XMLHttpRequest},function(){return new ActiveXObject("Msxml2.XMLHTTP")},function(){return new ActiveXObject("Msxml3.XMLHTTP")},function(){return new ActiveXObject("Microsoft.XMLHTTP")}],n=function(e){if(e=e.match(/^([a-zA-Z]*:?\/\/)?([^/]+)/))return e[2]},f=function(e,d){var c=Array.prototype.slice.call(arguments),b=d.headers||{},f=d.xhrFields||{},a=d.url||"",l=d.data||"",w=(d.type||"get").toUpperCase(),y=d.complete||function(){},x=d.error||function(){g.error("Error with url "+
a+"= "+c.join(","))},t=n(a),r=n(location.toString());(t="undefined"!=typeof XDomainRequest&&!(t&&r&&t==r))&&(e=new XDomainRequest);h.isPlainObject(l)&&("GET"==w?(a+=m.serialize(l),l=null):l=JSON.stringify(l));t?(e.open(w,a),e.onprogress=function(){},e.ontimeout=x,e.timeout=0):e.open(w,a,!0);k.merge(e,f);t||k.each(b,function(a,b){try{e.setRequestHeader(b,a)}catch(c){g.error("AJAX ERROR: Couldn't set request header "+b+" to "+a)}});var v=!1;e.onerror=function(a){v||(v=!0,x.call(e,e.statusText,e.status))};
b=function(){void 0!==e.readyState&&4!==e.readyState||v||(v=!0,String(e.status||200).match(/^[23]/)?"function"===typeof y?y.call(e,e.responseText):g.warn("`complete` callback must be a function."):x.call(e,e.statusText,e.status))};e.onload=b;e.onreadystatechange=b;e.send(l)};return function(e){e=e||{};var d;d=!1;for(var c=0;c<l.length;c++){try{d=l[c]()}catch(b){continue}break}f(d,e);return d}});
extole.define("https://origin.extole.io/type=core:clientId=1241766588:coreAssetsVersion=1544591110231/common/client/program.js",[],function(){return{getName:function(){return extole.PROGRAM.name},getProgramDomain:function(){return extole.PROGRAM.programDomain},getSitePatterns:function(){return extole.PROGRAM.sitePatterns},isSecure:function(){return Boolean(extole.PROGRAM.isSecure)},getProtocol:function(){return this.isSecure()?"https://":window.location.protocol.match(/^https/)?"https://":"http://"}}});
extole.define("https://origin.extole.io/type=core:clientId=1241766588:coreAssetsVersion=1544591110231/common/client/token-store.js",["https://origin.extole.io/type=core:clientId=1241766588:coreAssetsVersion=1544591110231/common/collection.js","https://origin.extole.io/type=core:clientId=1241766588:coreAssetsVersion=1544591110231/common/logger.js","https://origin.extole.io/type=core:clientId=1241766588:coreAssetsVersion=1544591110231/common/event-bus.js","https://origin.extole.io/type=core:clientId=1241766588:coreAssetsVersion=1544591110231/common/cookie.js",
"https://origin.extole.io/type=core:clientId=1241766588:coreAssetsVersion=1544591110231/common/client/program.js"],function(k,m,h,g,l){var n={year:365,YEAR:365,session:null,SESSION:null};return new function(){function f(){this.get=function(b){return g(b)};this.set=function(b,c,a){extole.COOKIES_DISABLED||g(b,c,{expires:n[a],path:"/",secure:l.isSecure()})};this.remove=function(b){g(b,"",{expires:-1,path:"/"})}}function e(){(function(){var b="test"+(new Date).getTime();try{localStorage.setItem(b,b),
localStorage.removeItem(b)}catch(c){throw Error("Local storage not supported");}})();this.get=function(b){return window.localStorage.getItem(b)};this.set=function(b,c,a){window.localStorage.setItem(b,c)};this.remove=function(b){window.localStorage.removeItem(b)}}var d=[],c=extole.CORE_CONFIG.cookieConsentEnabled?"SESSION":"YEAR";d.push(new function(){var b={};this.get=function(c){return b[c]};this.set=function(c,a,d){b[c]=a};this.remove=function(c){delete b[c]}});extole.COOKIES_DISABLED||d.push(new f);
if(extole.LOCAL_STORAGE_ENABLED)try{d.push(new e)}catch(b){m.info("Local Storage not supported in current browser")}this.events=h.create();this.get=function(){for(var b,c=0;c<d.length;c++){b=d[c];var a=b.get("extole_access_token");if(Boolean("string"===typeof a&&"undefined"!==a&&"null"!==a&&a.length))return b.get("extole_access_token")}return null};this.set=function(b,e){var a=this.get();c=e||c;k.each(d,function(a){a.set("extole_access_token",b,c)});a!==b&&this.events.trigger("change:access_token");
a&&a!=b&&m.debug("ACCESS_TOKEN_CHANGE - the access token changed from: "+a+", to: "+b)};this.remove=function(){k.each(d,function(b){b.remove("extole_access_token")})}}});
extole.define("CreativeRenderContext",["https://origin.extole.io/type=core:clientId=1241766588:coreAssetsVersion=1544591110231/common/uri.js","https://origin.extole.io/type=core:clientId=1241766588:coreAssetsVersion=1544591110231/common/collection.js"],function(k,m){function h(g,f,e){this.getElement=function(){return e};this.getName=function(){return g};this.getData=function(){return f};this.getParameters=function(){return f}}function g(){this.getName=function(){return extole.PROGRAM.name};this.getProgramDomain=
function(){return extole.PROGRAM.programDomain};this.getSitePatterns=function(){return extole.PROGRAM.sitePatterns}}function l(){this.backendTargetingEnabled=function(){return!0};this.cookieConsentEnabled=function(){return extole.CORE_CONFIG.cookieConsentEnabled}}return function(n,f,e,d){var c=new h(n,f,e),b=new g,p=new l;this.getZone=function(){return c};this.getProgram=function(){return b};this.getCreativeData=function(){var a=k.dotNotationToObject(k.deserialize(location.search)),b=k.dotNotationToObject(c.getParameters());
return m.merge(a.extole_creative,b.creative)};this.getCoreConfig=function(){return p};this.getLocale=function(){return d||null}}});
extole.define("find-element-by-id",["https://origin.extole.io/type=core:clientId=1241766588:coreAssetsVersion=1544591110231/common/logger.js"],function(k){function m(h,g,l){function k(){if(g())l();else{h();var e=setTimeout,d;f||(f=10);d=500<f?500:f*=1.1;e(k,d)}}var f;k()}return function(h,g){var l=(new Date).getTime(),n=!1,f;m(function(){f=document.getElementById(h)},function(){var e=(new Date).getTime()-l;!n&&5E3<e&&(n=!0,k.info("Scanned for 5000 ms searching for zone element id: "+h));return Boolean(f)},
function(){g(f)})}});
extole.define("pending-zone-service",["find-element-by-id","https://origin.extole.io/type=core:clientId=1241766588:coreAssetsVersion=1544591110231/common/logger.js","https://origin.extole.io/type=core:clientId=1241766588:coreAssetsVersion=1544591110231/common/collection.js","https://origin.extole.io/type=core:clientId=1241766588:coreAssetsVersion=1544591110231/common/client/token-store.js","CreativeRenderContext"],function(k,m,h,g,l){function n(c,b){c.element?b(c.element):c.element_id?k(c.element_id,
b):b(document.body.appendChild(document.createElement("DIV")))}function f(c){c=h.merge({},c);delete c.campaign_id;delete c.extole_campaign_id;return c}var e={},d=function(c,b){b=b||function(){};var d=c.name,a=f(c.data||c.parameters||{});this.resolve=function(e,f,h,k){g.set(f,h);n(c,function(c){c=new l(d,a,c,k);e(c);b(null,c.getZone())})}};return{get:function(c){if(!e[c])throw Error("Pending zone does not exist for id: "+c);return e[c]},create:function(){var c=Math.floor(1E9*Math.random()),b=0;return function(f,
a){b++;var g=c+"."+b;e[g]=new d(f,a);return g}}()}});
extole.define("create-zone","https://origin.extole.io/type=core:clientId=1241766588:coreAssetsVersion=1544591110231/common/uri.js https://origin.extole.io/type=core:clientId=1241766588:coreAssetsVersion=1544591110231/common/collection.js https://origin.extole.io/type=core:clientId=1241766588:coreAssetsVersion=1544591110231/common/type.js https://origin.extole.io/type=core:clientId=1241766588:coreAssetsVersion=1544591110231/common/dom.js https://origin.extole.io/type=core:clientId=1241766588:coreAssetsVersion=1544591110231/common/client/program.js https://origin.extole.io/type=core:clientId=1241766588:coreAssetsVersion=1544591110231/common/client/token-store.js pending-zone-service".split(" "),function(k,
m,h,g,l,n,f){function e(c){var b=document.createElement("script");g.setAttribute(b,"src",c);g.setAttribute(b,"async","");g.append(g.query("head")[0],b);return b}function d(c){function b(a,c){if(h.isPlainObject(a))m.each(a,function(a,d){var e=c.slice();e.push(d);b(a,e)});else{var e=c.join(".");d[e]=a}}var d={};b(c,[]);return d}return function(c,b,g){b=b||function(){};var a=[l.getProtocol(),l.getProgramDomain(),"/zone/",c.name].join(""),h=m.merge({extole_app:"javascript_sdk"},d(c.data||c.parameters||
{}));n.get()&&(h.access_token=n.get());h.zone_id=f.create(c,b);e(a+k.serialize(h)).onload=function(){"function"===typeof g&&setTimeout(g,500)}}});
extole.define("create-zone-executor",["create-zone","https://origin.extole.io/type=core:clientId=1241766588:coreAssetsVersion=1544591110231/common/logger.js"],function(k,m){function h(g){var f=!1;return function(){var e=Array.prototype.slice.call(arguments);f||(f=!0,g.apply(null,e))}}var g=new function(){var g=0,f=[],e=this;this.push=function(d){f.push(d);this.next()};this.next=function(){for(var d=function(){g--;e.next()};1>g&&f.length;)f.shift()(d),g++}},l=0;return{execute:function(n,f){f=f||function(){};
-1!==["conversion","confirmation"].indexOf(n.name)&&m.info("CRITICAL_ZONE_REQUEST - ### "+JSON.stringify(n)+" ###");0===l?g.push(function(e){e=h(e);k(n,function(){var d=Array.prototype.slice.call(arguments);f.apply(null,d);e()},e)}):g.push(function(e){k(n,f);e()});l++}}});
extole.define("https://origin.extole.io/type=core:clientId=1241766588:coreAssetsVersion=1544591110231/legacy-tag-scanning-service.js",[],function(){var k={};k.validators=function(){return{isEmail:function(h){h=String(h);h=h.replace(/^\s+/,"").replace(/\s+$/,"");return h.match(/^((([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*)|((\x22)((((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(([\x01-\x08\x0b\x0c\x0e-\x1f\x7f]|\x21|[\x23-\x5b]|[\x5d-\x7e]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(\\([\x01-\x09\x0b\x0c\x0d-\x7f]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]))))*(((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(\x22)))@((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))$/i)}}}();
k.logger=function(){(function(h,g,l,k,f){h[g]=h[g]||{};for(h[g].q=h[g].q||[];f<k.length;)l(k[f++],h[g])})(window,"extole",function(h,g){g[h]=g[h]||function(){g.q.push([h,arguments])}},["log"],0);return{debug:function(h,g){window.extole.log("DEBUG",h,g)},info:function(h,g){window.extole.log("INFO",h,g)},warn:function(h,g){window.extole.log("WARN",h,g)},error:function(h,g){window.extole.log("ERROR",h,g)}}}();k["utils-collections"]=function(){var h=Array.prototype.slice,g=function(b,c){return Object.prototype.hasOwnProperty.call(b,
c)},l=function(b){if(!f(b))return[];var c=[],a;for(a in b)g(b,a)&&c.push(a);return c},k=function(b){for(var c=l(b),a=c.length,d=Array(a),e=0;e<a;e++)d[e]=b[c[e]];return d},f=function(b){if("[object Object]"!==String(b)||b.nodeType||b.window&&b.window==b)return!1;try{if(b.constructor&&!b.constructor.prototype.hasOwnProperty("isPrototypeOf"))return!1}catch(c){return!1}return!0},e=function(b){return b instanceof Array},d=function(b,c){var a,d;if(b.length===+b.length)for(d=0;d<b.length;d++){if(a=c(b[d],
d),!1===a)return!1}else for(d in b)if(b.hasOwnProperty(d)&&(a=c(b[d],d),!1===a))return!1};d.BREAK=!1;var c=function(b,c){var a=[];d(b,function(b,d){var e=c(b,d);void 0!==e&&a.push(e)});return a};return{each:d,map:c,mapObj:function(b,c){var a={};d(b,function(b,d){var e=c(b,d);void 0!==e&&(e.key&&e.value?a[e.key]=e.value:a[d]=e)});return a},has:g,keys:l,values:k,invert:function(b){for(var c={},a=l(b),d=0,e=a.length;d<e;d++)c[b[a[d]]]=a[d];return c},toArray:function(b){return b?e(b)?h.call(b):b.length===
+b.length?c(b,function(b){return b}):k(b):[]},inArray:function(b,c,a){var d;if(c)for(d=c.length,a=a?0>a?Math.max(0,d+a):a:0;a<d;a++)if(a in c&&c[a]===b)return a;return-1},isArray:e,isPlainObject:f}}();k.JSON=function(){var h;"object"!==typeof h&&(h={});(function(){function g(a){return 10>a?"0"+a:a}function k(a){e.lastIndex=0;return e.test(a)?'"'+a.replace(e,function(a){var c=b[a];return"string"===typeof c?c:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function n(a,b){var e,
f,h,m,r=d,v,u=b[a];u&&u instanceof Date&&(e=u,u=isFinite(e.valueOf())?e.getUTCFullYear()+"-"+g(e.getUTCMonth()+1)+"-"+g(e.getUTCDate())+"T"+g(e.getUTCHours())+":"+g(e.getUTCMinutes())+":"+g(e.getUTCSeconds())+"Z":null);"function"===typeof p&&(u=p.call(b,a,u));switch(typeof u){case "string":return k(u);case "number":return isFinite(u)?String(u):"null";case "boolean":case "null":return String(u);case "object":if(!u)return"null";d+=c;v=[];if("[object Array]"===Object.prototype.toString.apply(u)){m=u.length;
for(e=0;e<m;e+=1)v[e]=n(e,u)||"null";h=0===v.length?"[]":d?"[\n"+d+v.join(",\n"+d)+"\n"+r+"]":"["+v.join(",")+"]";d=r;return h}if(p&&"object"===typeof p)for(m=p.length,e=0;e<m;e+=1)"string"===typeof p[e]&&(f=p[e],(h=n(f,u))&&v.push(k(f)+(d?": ":":")+h));else for(f in u)Object.prototype.hasOwnProperty.call(u,f)&&(h=n(f,u))&&v.push(k(f)+(d?": ":":")+h);h=0===v.length?"{}":d?"{\n"+d+v.join(",\n"+d)+"\n"+r+"}":"{"+v.join(",")+"}";d=r;return h}}var f,e,d,c,b,p;"function"!==typeof h.stringify&&(e=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
b={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},h.stringify=function(a,b,e){var f;c=d="";if("number"===typeof e)for(f=0;f<e;f+=1)c+=" ";else"string"===typeof e&&(c=e);if((p=b)&&"function"!==typeof b&&("object"!==typeof b||"number"!==typeof b.length))throw Error("JSON.stringify");return n("",{"":a})});"function"!==typeof h.parse&&(f=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,h.parse=function(a,b){function c(a,
d){var e,f,g=a[d];if(g&&"object"===typeof g)for(e in g)Object.prototype.hasOwnProperty.call(g,e)&&(f=c(g,e),void 0!==f?g[e]=f:delete g[e]);return b.call(a,d,g)}var d;a=String(a);f.lastIndex=0;f.test(a)&&(a=a.replace(f,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return d=eval("("+
a+")"),"function"===typeof b?c({"":d},""):d;throw new SyntaxError("JSON.parse");})})();return h}();k.utils=function(h,g){var k=h.each,n=h.map,f=h.mapObj,e=h.has,d=h.keys,c=h.values,b=h.invert,p=h.toArray,a=h.inArray,m=h.isArray,w=h.isPlainObject,y=0,x=function(a){return a&&"function"===typeof a&&a.call&&a.apply};"undefined"!=typeof window.console&&(extole.console=extole.console||console);var t;t=function(){var a,b,c,d,e,f=arguments[0]||{},g=1,h=arguments.length,k=!1;"boolean"===typeof f&&(k=f,f=arguments[1]||
{},g=2);for("object"===typeof f||x(f)||(f={});g<h;g++)if(a=arguments[g],null!==a)for(b in a)c=f[b],d=a[b],f!==d&&(k&&d&&(w(d)||(e=m(d)))?(e?(e=!1,c=c&&m(c)?c:[]):c=c&&w(c)?c:{},f[b]=t(k,c,d)):void 0!==d&&(f[b]=d));return f};var r=Array.prototype.slice,v=function(){g.debug.apply(null,arguments)};v.debug=g.debug;v.warn=g.warn;v.info=g.info;v.error=g.error;var u=extole.generalReady;extole.generalReady||(u=extole.generalReady=function(a){extole._generalReadyAnonKey||(extole._generalReadyAnonKey=0);var b=
extole._generalReadyAnonKey++;a=t(a||{},{readyTest:void 0});u.readies[b]||(u.readies[b]={ready:!1,funcs:[]});var c=function(a){a||u.readies[b].ready?u.readies[b].funcs.push(a):(u.readies[b].ready=!0,v.debug("** generalReady ** "+b+" - set ready"));if(u.readies[b].ready)for(;a=u.readies[b].funcs.pop();)setTimeout(a,0)};c.unset=function(){u.readies[b].ready=!1};c.set=function(){c()};c.isReady=function(){return u.readies[b].ready};return c},u.readies={});var z=function(a,b){b||(b=a,a="undefined");var c=
Error("TYPE: "+a+"  MESSAGE: "+b);c.type=a;return c};return{uniqueId:function(a){var b=++y+"";return a?a+b:b},each:k,map:n,mapObj:f,has:e,keys:d,values:c,invert:b,toArray:p,inArray:a,isEmpty:function(a){if(null===a)return!0;if(m(a)||"string"===typeof a)return 0===a.length;for(var b in a)if(e(a,b))return!1;return!0},isArray:m,isPlainObject:w,isFunction:x,proxy:function(a,b){var c;a.__proxiedContext===b?c=a:(c=function(){return a.apply(b,arguments)},c.__proxiedContext=b);return c},log:v,generalReady:u,
extend:t,defaults:function(a){k(r.call(arguments,1),function(b){if(b)for(var c in b)void 0===a[c]&&(a[c]=b[c])});return a},createObject:Object.create||function(a){var b=function(){};b.prototype=a;return new b},typedError:z,throwError:function(a,b){throw z(a,b);},handleError:function(a,b,c){c=c||function(){};try{b()}catch(d){if(d.type==a)return c(d),d;throw d;}},location:{serialize:function(a){var b="";utils.each(a,function(a,c){void 0!==c&&void 0!==a&&(b+="&"+encodeURIComponent(c)+"="+encodeURIComponent(String(a)))});
0<b.length&&(b="?"+b.slice(1));return b},deserialize:function(a){if(!a)return{};var b={};a=a.substring(1).split("&");for(var c=0;c<a.length;c++){var d=a[c],e=d.substring(0,d.indexOf("=")),d=d.substring(d.indexOf("=")+1);if(e&&d)try{b[e]=decodeURIComponent(d)}catch(f){utils.log("Bad Query Param "+e+" : "+d)}}return b}}}}(k["utils-collections"],k.logger);k.params=function(h,g){var k={e:"email",f:"first_name",l:"last_name"},n="email first_name last_name source partner_conversion_id partner_user_id".split(" ");
return{rekey:function(f){var e={};h.each(f,function(d,c){k[c]&&(c=k[c]);var b=/^tag:/.test(c),f=-1<h.inArray(c,n)?!0:!1;b||f||(c="tag:"+c);e[c]=d});return e},split:function(f,e){e=h.extend({validateEmail:!0},e||{});var d={init:{},client:{}};if(!f)return d;h.each(f,function(c,b){var f=d.init;-1<b.indexOf("tag:")?(b=b.substring(4),f=d.client):"email"==b&&e.validateEmail&&!g.isEmail(c)&&(h.log("Initialized with invalid email address ("+c+") - (configUtils.getInitParams)"),c=void 0);f[b]=c});return d},
removeTags:function(f){var e={};h.each(f,function(d,c){c=c.replace(/^tag:/,"");e[c]=d});return e}}}(k.utils,k.validators);k["event-bus"]=function(){function h(){this._events={};var h=/\s+/,f=function(d,c,b,e){if(!b)return!0;if("object"===typeof b){for(var a in b)d[c].apply(d,[a,b[a]].concat(e));return!1}if(h.test(b)){b=b.split(h);a=0;for(var f=b.length;a<f;a++)d[c].apply(d,[b[a]].concat(e));return!1}return!0},e=function(d,c){var b,e=-1,a=d.length,f=c[0],g=c[1],h=c[2];switch(c.length){case 0:for(;++e<
a;){(b=d[e]).callback.call(b.ctx);return}case 1:for(;++e<a;){(b=d[e]).callback.call(b.ctx,f);return}case 2:for(;++e<a;){(b=d[e]).callback.call(b.ctx,f,g);return}case 3:for(;++e<a;){(b=d[e]).callback.call(b.ctx,f,g,h);return}default:for(;++e<a;){(b=d[e]).callback.apply(b.ctx,c);break}}};this.on=function(d,c,b){if(!f(this,"on",d,[c,b])||!c)return this;this._events||(this._events={});(this._events[d]||(this._events[d]=[])).push({callback:c,context:b,ctx:b||this});return this};this.off=function(d,c,b){var e,
a,g,h,n,m,t,r;if(!this._events||!f(this,"off",d,[c,b]))return this;if(!d&&!c&&!b)return this._events=void 0,this;h=d?[d]:k.keys(this._events);n=0;for(m=h.length;n<m;n++)if(d=h[n],g=this._events[d]){this._events[d]=e=[];if(c||b)for(t=0,r=g.length;t<r;t++)a=g[t],(c&&c!==a.callback&&c!==a.callback._callback||b&&b!==a.context)&&e.push(a);e.length||delete this._events[d]}return this};this.once=function(d,c,b){var e=this,a=function(){var f=g.call(arguments);c.apply(this,f);e.off(d,a,b)};this.on(d,a,b);
return this};this.trigger=function(d){if(!this._events)return this;var c=g.call(arguments,1);if(!f(this,"trigger",d,c))return this;var b=this._events[d],h=this._events.all;b&&e(b,c);h&&e(h,arguments);return this}}var g=Array.prototype.slice,k={isPlainObject:function(g){if("[object Object]"!==String(g)||g.nodeType||g.window&&g.window==g)return!1;try{if(g.constructor&&!g.constructor.prototype.hasOwnProperty("isPrototypeOf"))return!1}catch(f){return!1}return!0},keys:function(g){if(!this.isPlainObject(g))return[];
var f=[],e;for(e in g)has(g,e)&&f.push(e);return f},_idCounter:0,uniqueId:function(g){var f=++this._idCounter+"";return g?g+f:f}};return{create:function(){return new h}}}();k["zone-event-bus"]=function(h){var g=h.create();return{publish:function(h,k,f){Array.prototype.slice.call(arguments);g.trigger("zone",h,k,f)},subscribe:function(h){g.on("zone",h)}}}(k["event-bus"]);k["zone-convert"]=function(h,g,k){function n(f){var e=f.code||"",d=f.description||"";this.stack=Error(d).stack;this.getCode=function(){return e};
this.getDescription=function(){return d}}n.prototype=Error();n.prototype.constructor=n;return function(f,e){e=e||function(){};var d=function(b){var c;b=(b||"").toLowerCase();if("purchase"===b)c="conversion";else if("register"===b||"registration"===b)c="registration";return c||null}(f.type),c=function(b){b=g.rekey(b);return g.removeTags(b)}(f.parameters||{});if(!d)return d="Error: could not find zone based on type:"+f.type,k.error(d),d=new n({description:d,code:"error-no-type"}),e(d);h.publish(d,null,
c)}}(k["zone-event-bus"],k.params,k.logger);k["dom-ready"]=function(h){var g=h.generalReady();(function(){var h;document.addEventListener?h=function(){document.removeEventListener("DOMContentLoaded",h,!1);g.set()}:document.attachEvent&&(h=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",h),g.set())});"complete"===document.readyState&&g.set();document.addEventListener?(document.addEventListener("DOMContentLoaded",h,!1),window.addEventListener("load",g.set,!1)):
document.attachEvent&&(document.attachEvent("onreadystatechange",h),window.attachEvent("onload",g.set))})();return g}(k.utils);k["dom-query"]=function(){return function(h,g){return(g||document).querySelectorAll(h)}}();k["page-scanner"]=function(h,g,k){function n(){function c(){d||(f=!1,d=!0,setTimeout(function(){for(var g={},n=a.splice(0,a.length);0<n.length;){var m=n.shift(),t=g[m.selector];if(!t)try{t=k(m.selector)}catch(r){h.log.error("query error -"+m.selector)}t&&0<t.length&&m.withElements(t);
m.shouldDelete()||a.push(m)}d=!1;f?c():e||(g=Math.ceil(50*(.3*Math.pow(1.017,b/50)+.7)),setTimeout(c,g),b=g)},1))}var b=0,d=!1,a=[],f=!1;this.queue=function(b){a.push(b);f=!0;d||c()};this.scan=c}function f(c){var b=0,d=function(){return!0},a=function(){},e=!1;this.withElements=function(c){h.each(c,function(b){d(b)&&a(b)});b++};this.setFilter=this.andIts=function(a){d=a;return this};this.setCompleted=this.thenCall=function(b){a=b;return this};this.setDeleteAfterCall=this.andRemove=function(){e=!0};
this.shouldDelete=function(){return 0<b&&!0===e?!0:!1};this.selector=c}var e=!1;g(function(){e=!0});var d=new n;return{whenYouFind:function(c){var b=new f(c);setTimeout(function(){d.queue(b)},1);return b},findAllTheThings:function(){d.scan()},reset:function(){d=new n}}}(k.utils,k["dom-ready"],k["dom-query"]);k["config-utils"]=function(h,g){return{getSharedVars:function(){for(var k=document.getElementsByTagName("script"),m={},f,e=0;e<k.length;e++)if("extole/context"==k[e].type){f=void 0;try{f=h.parse(k[e].innerHTML)}catch(d){g.log.error("Bad JSON in context script tag.")}f&&
g.extend(m,f)}return m}}}(k.JSON,k.utils);k["creative-placement"]=function(h,g){var k=function(e,d){var c=e;"none"!==d&&(c=document.createElement("span"));return c},m=function(e,d,c,b){var f=arguments,a=d.parentNode;if(!a)return g(function(){a||(document.body.appendChild(d),m.apply(null,f))}),!1;"replace"==c?(a.insertBefore(e,d),a.removeChild(d)):"before"==c?a.insertBefore(e,d):"after"==c?d.nextSibling?a.insertBefore(e,d.nextSibling):a.appendChild(e):"inside"==c&&d.appendChild(e);b(null)},f=function(e){e=
h.extend({insertPosition:void 0,referenceElement:void 0},e||{});var d=e.insertPosition;e=e.referenceElement;d||(d="before","*"==e?d="inside":e&&(d="none"));return d};return{renderElement:function(e,d){var c=e.getData(),c=f({insertPosition:c.insert_position,referenceElement:c.reference_element}),b=e.element,g=k(b,c);m(g,b,c,function(){d(null,g)});return g},getInsertPosition:f}}(k.utils,k["dom-ready"]);k["zone-factory"]=function(h,g){var k=[],m={elementReady:function(e){var d=this;g.renderElement(this,
function(c,b){d.element=b;e&&e(c,b)})},shouldShowDefaultContent:function(){return!1},renderDefaultContent:function(){},getConfig:function(){return{}},getInsertPosition:function(){return g.getInsertPosition({insertPosition:this.data.insert_position,referenceElement:this.data.reference_element})},getData:function(){return this.data},getType:function(){return this.type||"cta"},getName:function(){return this.name&&this.name.toLowerCase()},getParameters:function(){return h.extend({},this.data.parameters,
this.data.params)},removeCampaignReferences:function(){this.data.parameters&&delete this.data.parameters.campaign_id;this.data.params&&delete this.data.params.campaign_id;this.campaign&&delete this.campaign},destroy:function(){this.element&&this.element.parentNode&&this.element.parentNode.removeChild(this.element);for(var e=0;e<k.length&&k[e]!=this;e++);k.splice(e,1)}},f=function(e){var d;d=e||{};!0!==d.__created&&(d=h.createObject(m),h.extend(d,e),k.push(d),d.__created=!0);return d};h.extend(f,{getZones:function(){return k}});
return f}(k.utils,k["creative-placement"]);k["zones-requester"]=function(h,g,k,m,f,e){function d(c){function b(b,a){a=a||function(){};var d;d=b.reference_element&&"*"==b.reference_element?"body":b.reference_element?b.reference_element:!1;if(!d)return a(null,c);m.whenYouFind(d).thenCall(function(b){a(null,b)}).andRemove()}this.prepare=function(d){d=d||function(){};var a;try{a=h.parse(c.innerHTML)}catch(e){return d(Error("element has bad JSON, can't make zone. html: "+c.innerHTML))}var f=(a.zone||"default").toLowerCase(),
k=g.extend(!0,{},a);b(k,function(a,b){if(a)return d(a);d(null,f,{id:{}.id,element:b,data:k})})}}return new function(){function c(){h||m.whenYouFind('script[type="extole/widget"]').thenCall(function(a){a.hasBeenUsed||(a.hasBeenUsed=!0,(new d(a)).prepare(function(a,c,d){if(a)return g.log("couldn't prepare page request "+a.message);b(c,d)}))});h=!0;m.findAllTheThings()}function b(a,b){b=b||{};var c=f(g.extend({name:a,type:a},b));c.elementReady(function(a,b){var d=c.getName(),f=c.getParameters();c.campaign&&
(f.campaign_id=c.campaign.id);e.publish(d,b,f)})}var h=!1;this.start=function(){c()};this.request=b}}(k.JSON,k.utils,k["dom-ready"],k["page-scanner"],k["zone-factory"],k["zone-event-bus"]);k.zones={requester:k["zones-requester"]};var m=new function(){var h=k["page-scanner"],g=k.zones,l=k.JSON,m=k.utils,f=k["zone-convert"],e=k["config-utils"],d=k["zone-event-bus"],c=function(){h.whenYouFind('script[type="extole/conversion"]').thenCall(function(b){if(!b.hasBeenUsed){b.hasBeenUsed=!0;a:{var a={};try{a=
l.parse(b.innerHTML)}catch(c){m.log.error("Could not fire conversion. "+c);break a}b=a.type||a.event_type;a=m.extend(!0,{},e.getSharedVars(),a);f({type:b,parameters:a.params})}}}).andRemove();h.findAllTheThings()},b=!1;this.start=function(){if(b)throw Error("legacy-tag-scanning service has already been started");b=!0;g.requester.start();c();d.subscribe(function(b,a,c){extole.createZone({name:b,element:a,data:c})})}};m.start();return m});